version: '3.8'

services:
  backend:
    image: ashishlal2003/recapai-backend:latest  # Ensure the repository and tag are correct
    environment:
      - OPENAI_KEY:${OPENAI_KEY}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  client:
    image: ashishlal2003/recapai-client:latest  # Ensure the repository and tag are correct
    ports:
      - "3000:3000"
